Repository nimblehq/stylelint-config-nimble, pull requests merged in 2023-07, with the labels that each got.

#14 Support Node >= 16
  package-lock.json
  packages/stylelint-config-nimble/package.json
Labels: type : chore

#15 Release 1.0.3
  .tool-versions
  package-lock.json
  packages/stylelint-config-nimble/.eslintrc.js
  packages/stylelint-config-nimble/lib/index.js
  packages/stylelint-config-nimble/package.json
Labels: type : release

#16 Fix publish pipeline
  .github/workflows/lint.yml
  .github/workflows/publish.yml
Labels: type : bug
